import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { distPath } from "./mount.mjs"
import { zipSync } from "./zip.mjs"

/**
 * The path the approuter serves this app under, once it is in the HTML5
 * Application Repository: the manifest's sap.app.id with the dots removed.
 * Read from the manifest rather than hardcoded, so it stays right if the app id
 * ever changes.
 */
export function appPath(dist = distPath()) {
  const manifest = JSON.parse(readFileSync(join(dist, "manifest.json"), "utf8"))
  const id = manifest?.["sap.app"]?.id
  if (!id) throw new Error(`${join(dist, "manifest.json")} has no sap.app.id`)
  return id.replaceAll(".", "")
}

/**
 * Marks a directory as generated by this command. Its presence is what makes
 * overwriting safe: without it we would be recursively writing over a path the
 * consumer named on the command line, which may be a directory they care about.
 */
export const MARKER = ".cap-agent-ui5-webui-generated"

/**
 * The approuter config that ships inside the app archive.
 *
 * Only one route is interesting. The UI fetches "agents.json" *relative* to its
 * own page, so once the app is served from the HTML5 Application Repository at
 * /<appId>/ that request becomes /<appId>/agents.json - a path the repository
 * has no file for, and could not have: agents.json is generated at runtime by
 * the CDS server from the services carrying @agent. This route sends it back to
 * the CAP service, at whatever mountPath the plugin is configured with there.
 *
 * The A2A calls need no route. agents.json returns absolute paths
 * ("/a2a/support"), which the approuter's own xs-app.json already forwards.
 *
 * The static route says "html5-apps-repo-rt", the name of the bound
 * app-runtime service. Plenty of examples use "html5-apps-repo" here, and that
 * works under the managed approuter because it skips the check - but a
 * standalone approuter fetches this file from the repository and validates it
 * on every request, answering 500 with "A route requires access to
 * html5-apps-repo service but the service is not bound" even though the
 * binding is fine.
 */
export function xsAppJson({ mountPath = "/chat", destination = "srv-api" } = {}) {
  return {
    welcomeFile: "/index.html",
    authenticationMethod: "route",
    routes: [
      {
        source: "^/agents\\.json$",
        target: `${mountPath}/agents.json`,
        destination,
        authenticationType: "xsuaa",
        csrfProtection: false,
      },
      {
        source: "^(.*)$",
        target: "$1",
        service: "html5-apps-repo-rt",
        authenticationType: "xsuaa",
      },
    ],
  }
}

/**
 * Routes to add to the *approuter's* own xs-app.json, ahead of any catch-all.
 *
 * The bundled xs-app.json above travels inside the archive and is what the
 * approuter applies when it resolves the app dynamically from the repository.
 * These are the explicit equivalent, and they are what a standalone approuter
 * with a catch-all route needs: that catch-all matches /<appPath>/... first and
 * forwards the whole app to the CAP service, which serves none of it.
 *
 * Both files name the service "html5-apps-repo-rt" - see xsAppJson above for
 * why the more commonly seen "html5-apps-repo" breaks a standalone approuter.
 */
export function routerRoutes({ mountPath = "/chat", destination = "srv-api", path } = {}) {
  return [
    {
      source: `^/${path}/agents\\.json$`,
      target: `${mountPath}/agents.json`,
      destination,
      authenticationType: "xsuaa",
      csrfProtection: false,
    },
    {
      source: `^/${path}/(.*)$`,
      target: "$1",
      service: "html5-apps-repo-rt",
      authenticationType: "xsuaa",
    },
  ]
}

/**
 * Write a deployable HTML5 Application Repository artifact into targetDir:
 * the prebuilt UI plus the xs-app.json above.
 *
 * Returns the entries written and the path the app will be served under, so a
 * caller can report what happened without re-reading the directory.
 */
export function prepareHtml5({
  targetDir,
  mountPath = "/chat",
  destination = "srv-api",
  archiveName,
  dist = distPath(),
} = {}) {
  if (!targetDir) throw new Error("prepareHtml5: targetDir is required")

  if (!existsSync(dist)) {
    throw new Error(
      `no built UI found at ${dist}. If you are working in a git clone, run \`npm run build\`; ` +
        `in an installed package this means it was published without dist/.`,
    )
  }

  // Refuse to overwrite anything this command did not create. The target is a
  // path from the command line, and this function writes over it wholesale.
  if (existsSync(targetDir)) {
    const entries = readdirSync(targetDir)
    if (entries.length && !entries.includes(MARKER)) {
      throw new Error(
        `${targetDir} is not empty and was not generated by this command ` +
          `(no ${MARKER} in it). Refusing to overwrite it — pass a different ` +
          `directory, or delete this one yourself if you meant to replace it.`,
      )
    }
  }

  mkdirSync(targetDir, { recursive: true })
  cpSync(dist, targetDir, { recursive: true })
  writeFileSync(
    join(targetDir, "xs-app.json"),
    `${JSON.stringify(xsAppJson({ mountPath, destination }), null, 2)}\n`,
  )
  writeFileSync(
    join(targetDir, MARKER),
    "Generated by `cap-agent-ui5-webui html5`. Safe to delete; do not edit by hand.\n",
  )

  const path = appPath(dist)

  // The archive is what actually gets deployed. mbt only *copies* an archive
  // the module's build produced - it never creates one - so without this the
  // content module uploads an empty payload and the repository answers
  // "Could not find applications in the request".
  //
  // It sits beside the unpacked files rather than replacing them: mbt picks up
  // the zip, and having the plain files there makes the artifact inspectable.
  const archive = `${archiveName ?? path}.zip`
  writeFileSync(join(targetDir, archive), zipSync(collectFiles(targetDir, [archive, MARKER])))

  return { entries: readdirSync(targetDir).sort(), path, archive }
}

/**
 * Every file under dir as { name, data }, with names relative to dir and
 * `exclude`d top-level entries left out — the archive must contain neither
 * itself nor the marker that tracks who generated the directory.
 */
function collectFiles(dir, exclude = []) {
  const out = []
  const walk = (current, prefix) => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const name = prefix ? `${prefix}/${entry.name}` : entry.name
      if (exclude.includes(name)) continue
      const full = join(current, entry.name)
      if (entry.isDirectory()) walk(full, name)
      else out.push({ name, data: readFileSync(full) })
    }
  }
  walk(dir, "")
  return out
}
